NumPy 배열(array) 생성하기
리스트로부터 배열 생성
리스트를 배열로 변환 
import numpy as np

# 리스트로부터 배열 생성
arr = np.array([1, 2, 3, 4, 5])
print(arr)

 

출력 결과
[1 2 3 4 5]

 

다양한 형태의 배열 생성
0으로 채워진 배열 생성
zero_arr = np.zeros((2, 3))  # 2x3 크기의 배열
print(zero_arr)

 

출력 결과
[[1. 1.]
 [1. 1.]
 [1. 1.]]

 

특정 값으로 채워진 배열 생성
full_arr = np.full((2, 2), 7)  # 2x2 크기의 7로 채워진 배열
print(full_arr)

 

출력 결과
[[7 7]
 [7 7]]

 

연속적인 값으로 채워진 배열 생성
range_arr = np.arange(10)  # 0부터 9까지의 연속된 값
print(range_arr)

 

출력 결과
[0 1 2 3 4 5 6 7 8 9]